/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shujie_changevoicelib_ChangeVoiceActivity */
#include <fmod.hpp>
#include <string>
#ifndef _Included_com_shujie_changevoicelib_ChangeVoiceActivity
#define _Included_com_shujie_changevoicelib_ChangeVoiceActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_shujie_changevoicelib_ChangeVoiceActivity_MODE_NOMAL
#define com_shujie_changevoicelib_ChangeVoiceActivity_MODE_NOMAL 0L
#undef com_shujie_changevoicelib_ChangeVoiceActivity_MODE_LUOLI
#define com_shujie_changevoicelib_ChangeVoiceActivity_MODE_LUOLI 1L
/*
 * Class:     com_shujie_changevoicelib_ChangeVoiceActivity
 * Method:    voiseChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_shujie_changevoicelib_ChangeVoiceActivity_voiseChangeNative
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
