/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shujie_ndksample_MainActivity */

#ifndef _Included_com_shujie_ndksample_MainActivity
#define _Included_com_shujie_ndksample_MainActivity

#ifdef __cplusplus
extern "C" {
#endif

#undef com_shujie_ndksample_MainActivity_number
#define com_shujie_ndksample_MainActivity_number 100L
/*
 * Class:     com_shujie_ndksample_MainActivity
 * Method:    testJNI
 * Signature: ()Ljava/lang/String;
 *//*
JNIEXPORT jstring
extern "C" jstring Java_com_shujie_ndksample_MainActivity_testJNI
  (JNIEnv *, jobject);*/

/*
 * Class:     com_shujie_ndksample_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 *//*
JNIEXPORT
extern "C" jstring JNICALL
Java_com_shujie_ndksample_MainActivity_stringFromJNI
  (JNIEnv *, jobject);*/

#ifdef __cplusplus
}
#endif
#endif